### PR TITLE
Add aiModule4.js

### PR DESCRIPTION
**Pull request by Prestonplayz334-js**
More AI responses added.

### CODE REVIEW

**Comment by tommystefanatic** [comment]
Try making a PR through dev because commiting to master is blocked for me.

**Comment by Prestonplayz334-js** [comment]
> Try making a PR through dev because commiting to master is blocked for me.

Done

**Comment by tommystefanatic** [comment]
Now we wait for @TechGeekGamer. :)

**Comment by Prestonplayz334-js** [comment]
Ok

**Pull request merged**
